"""Add is_answer column to Message model

Revision ID: 69062d5c9085
Revises: add_gd_rooms
Create Date: 2025-05-30 19:23:09.523864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69062d5c9085'
down_revision = 'add_gd_rooms'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_answer', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_answer')

    # ### end Alembic commands ###
