"""Initial migration to MySQL

Revision ID: 30e99c5f57d9
Revises: 
Create Date: 2025-05-31 21:55:48.779058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e99c5f57d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activity_level', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('current_intent', sa.String(length=50), nullable=True),
    sa.Column('intent_weights', sa.Text(), nullable=True),
    sa.Column('last_intent_update', sa.DateTime(), nullable=True),
    sa.Column('topic_data', sa.Text(), nullable=True),
    sa.Column('topic_hierarchy', sa.Text(), nullable=True),
    sa.Column('topic_coherence', sa.Float(), nullable=True),
    sa.Column('last_topic_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_gp', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gp_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points_all_time', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('last_task_completion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=True),
    sa.Column('is_answer', sa.Boolean(), nullable=True),
    sa.Column('points_offered', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('accepted_answer_id', sa.Integer(), nullable=True),
    sa.Column('rating_sum', sa.Integer(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('primary_emotion', sa.String(length=20), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('all_emotions', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(length=20), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('all_intents', sa.Text(), nullable=True),
    sa.Column('sentiment_compound', sa.Float(), nullable=True),
    sa.Column('sentiment_positive', sa.Float(), nullable=True),
    sa.Column('sentiment_negative', sa.Float(), nullable=True),
    sa.Column('sentiment_neutral', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=10), nullable=True),
    sa.Column('topics', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('sales_intent', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['accepted_answer_id'], ['message.id'], name='fk_message_accepted_answer', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['message.id'], name='fk_message_parent', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('subtopics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('rooms_joined', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('avg_sentiment_compound', sa.Float(), nullable=True),
    sa.Column('positive_message_count', sa.Integer(), nullable=True),
    sa.Column('negative_message_count', sa.Integer(), nullable=True),
    sa.Column('neutral_message_count', sa.Integer(), nullable=True),
    sa.Column('avg_message_length', sa.Float(), nullable=True),
    sa.Column('peak_activity_hours', sa.String(length=100), nullable=True),
    sa.Column('favorite_rooms', sa.String(length=200), nullable=True),
    sa.Column('topics_discussed', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language_preferences', sa.String(length=100), nullable=True),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('preferred_topics', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weekly_leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gp_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gp_id', 'week_number', 'year', name='unique_gp_week_year')
    )
    op.create_table('gp_task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gp_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'approved', 'rejected', name='task_status'), nullable=True),
    sa.Column('proof_text', sa.Text(), nullable=True),
    sa.Column('proof_file_path', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gp_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='unique_message_vote')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rated_user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['rated_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rater_id', 'message_id', name='unique_user_message_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('message_vote')
    op.drop_table('gp_task_status')
    op.drop_table('weekly_leaderboard')
    op.drop_table('user_profile')
    op.drop_table('user_metrics')
    op.drop_table('user_interest')
    op.drop_table('task')
    op.drop_table('room_topic')
    op.drop_table('room_membership')
    op.drop_table('message')
    op.drop_table('gp_profile')
    op.drop_table('user')
    op.drop_table('room')
    # ### end Alembic commands ###
