"""Add topic coherence fields to Room model

Revision ID: 335e03280259
Revises: ac8ee66d4195
Create Date: 2025-05-25 10:40:09.265539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335e03280259'
down_revision = 'ac8ee66d4195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_hierarchy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('topic_coherence', sa.Float(), nullable=True))
        batch_op.drop_column('last_summarized_message_id')
        batch_op.drop_column('last_summary_update')
        batch_op.drop_column('current_summary')

    with op.batch_alter_table('room_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coherence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtopics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_topic', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('subtopics')
        batch_op.drop_column('coherence_score')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('last_summary_update', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_summarized_message_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('topic_coherence')
        batch_op.drop_column('topic_hierarchy')

    # ### end Alembic commands ###
