"""Add topic_data and other columns to Room model

Revision ID: 5a3a1f91fecd
Revises: cf650fe73076
Create Date: 2025-05-25 09:38:00.192992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3a1f91fecd'
down_revision = 'cf650fe73076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_emotion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emotion_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('all_emotions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('intent', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('intent_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('all_intents', sa.Text(), nullable=True))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_data', sa.Text(), nullable=True))
        batch_op.drop_column('topic_distribution')
        batch_op.drop_column('topic_keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_keywords', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('topic_distribution', sa.TEXT(), nullable=True))
        batch_op.drop_column('topic_data')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('all_intents')
        batch_op.drop_column('intent_confidence')
        batch_op.drop_column('intent')
        batch_op.drop_column('all_emotions')
        batch_op.drop_column('emotion_score')
        batch_op.drop_column('primary_emotion')

    # ### end Alembic commands ###
