"""remove email verification

Revision ID: ac8ee66d4195
Revises: 0538fc509082
Create Date: 2025-05-25 10:06:02.442362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8ee66d4195'
down_revision = '0538fc509082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email_verification_token'), type_='unique')
        batch_op.drop_column('email_verification_sent_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verification_sent_at', sa.DATETIME(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email_verification_token'), ['email_verification_token'])

    # ### end Alembic commands ###
