"""Add topic modeling and summarization fields to Room model

Revision ID: cf650fe73076
Revises: dbe0de6ff115
Create Date: 2025-05-24 22:18:03.118504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf650fe73076'
down_revision = 'dbe0de6ff115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('topic_keywords', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_topic_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_summary_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_summarized_message_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('last_summarized_message_id')
        batch_op.drop_column('last_summary_update')
        batch_op.drop_column('current_summary')
        batch_op.drop_column('last_topic_update')
        batch_op.drop_column('topic_keywords')
        batch_op.drop_column('topic_distribution')

    # ### end Alembic commands ###
