"""Add avg_message_length to user_metrics

Revision ID: dbe0de6ff115
Revises: 
Create Date: 2025-05-24 21:51:41.623289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe0de6ff115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('engagement_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_sentiment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_message_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peak_activity_hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('favorite_rooms', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('topics_discussed', sa.String(length=500), nullable=True))

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('language_preferences', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('communication_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_topics', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('preferred_topics')
        batch_op.drop_column('communication_style')
        batch_op.drop_column('language_preferences')
        batch_op.drop_column('timezone')
        batch_op.drop_column('location')

    with op.batch_alter_table('user_metrics', schema=None) as batch_op:
        batch_op.drop_column('topics_discussed')
        batch_op.drop_column('favorite_rooms')
        batch_op.drop_column('peak_activity_hours')
        batch_op.drop_column('avg_message_length')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('is_private')
        batch_op.drop_column('language')
        batch_op.drop_column('avg_sentiment')
        batch_op.drop_column('engagement_rate')
        batch_op.drop_column('activity_level')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('word_count')
        batch_op.drop_column('language')
        batch_op.drop_column('topics')

    # ### end Alembic commands ###
