"""add state field to user model

Revision ID: fa33581afddf
Revises: insert_predefined_rooms
Create Date: 2024-03-19 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa33581afddf'
down_revision = 'insert_predefined_rooms'
branch_labels = None
depends_on = None


def upgrade():
    # Add state column as nullable first
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
    
    # Update existing users to have a default state
    op.execute("UPDATE user SET state = 'Delhi' WHERE state IS NULL")
    
    # Now make the column non-nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('state',
                            existing_type=sa.String(length=50),
                            nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
